from typing import Protocol, List, Optional
from datetime import datetime

class RestaurantRepositoryInterface(Protocol):
    async def get_all_restaurants(self, limit: int, offset: int) -> List[dict]: ...
    async def get_restaurant_by_id(self, restaurant_id: str) -> Optional[dict]: ...
    async def search_restaurants(self, query: str) -> List[dict]: ...
    async def count_occupied_tables(self, table_type_id: str, time_window_start: datetime, time_window_end: datetime) -> int: ...
    async def get_table_type_details(self, table_type_id: str) -> Optional[dict]: ...
    async def get_reservations_in_window(self, start_time: datetime, end_time: datetime) -> List[dict]: ...

# Dejamos dos espacios en blanco para separar los bloques de firmas
class CacheInterface(Protocol):
    async def get(self, key: str) -> Optional[str]: ...
    async def set(self, key: str, value: str, expire: int = 60) -> None: ...