# Ocultar la versión de Nginx en los headers [cite: 875]
server_tokens off;

server {
    listen 80;
    server_name localhost;

    # Ocultar la versión de Nginx (Requerimiento del examen) [cite: 70]
    server_tokens off;

    # Tiempos de espera estándar [cite: 71]
    proxy_connect_timeout 60s;
    proxy_read_timeout 60s;

    # 1. Frontend Estático
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # 2. Django Admin [cite: 67]
    location /admin/ {
        proxy_pass http://django-app:8000;  # <-- Apunta al nuevo nombre con guion medio
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Estáticos de Django sirviéndose directo [cite: 69]
    location /static/ {
        alias /app/static/;
    }

    # 3. FastAPI [cite: 68]
    location /api/ {
        proxy_pass http://fastapi-app:8080;  # <-- Apunta al nuevo nombre con guion medio
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Manejo de Errores genérico [cite: 73]
    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}